### PR TITLE
Add upload capability

### PR DESCRIPTION
**Pull request by flyte**
Enable uploading gifs to Giphy.

```
In [1]: import giphypop

In [2]: g = giphypop.Giphy()
giphypop.py:240: UserWarning: You are using the giphy public api key. This should be used for testing only and may be deactivated in the future. See https://github.com/Giphy/GiphyAPI.
  warnings.warn('You are using the giphy public api key. This '

In [3]: gif = g.upload(["test"], "/home/flyte/Videos/gif/output.gif")
gif

In [4]: gif
Out[4]: GiphyImage<3o72F1yGknib10Gfis> at http://giphy.com/gifs/test-3o72F1yGknib10Gfis
```

### CODE REVIEW

**Comment by flyte** [comment]
I'm in a bit of a hurry so I haven't done tests or updated the readme. If you're happy to add this functionality then don't merge yet and I'll add tests and instructions in the readme.

**Comment by shaunduncan** [comment]
I'm so sorry for the delay. I didn't even realize giphy had introduced an upload api, so I think this is really cool! I think it would be helpful for folks to have an example on how to use this in the readme. Would you be able to add that? Otherwise, I think that this looks great. Thank you for the contribution!

**Comment by flyte** [comment]
No worries, I'll add this to the readme at some point soon and update this PR.

**Comment by flyte** [comment]
@shaunduncan Ready to merge now if everything looks OK to you.

**Comment by shaunduncan** [comment]
Sorry I didn't respond to this sooner, but this is fantastic. I'll merge it and upload a new version to pypi. Thank you!

**Pull request merged**
